### ISSUE TITLE
Pull/Issue message parsing quirks

### ISSUE THREAD

**Issue by GreenXenith** [GreenXenith/minetestbot#4]
Linking to issue/pull should only occur if # is:
- Not inside a codeblock
- At the beginning of line or preceded by whitespace (eg, not `param#1`)
- Not inside a link (this should be fixed by the previous requirement)
- Greater than 99

**Comment by appgurueu** [comment]
> Not inside a codeblock

Agreed.

> At the beginning of line or preceded by whitespace (eg, not param#1)

Agreed.

> Not inside a link (this should be fixed by the previous requirement)

Indeed, previous requirement should fix this.

> Greater than 99

That heuristic seems pretty random to me.
